name: Full CI/CD Pipeline
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Kodni olish (Checkout)
        uses: actions/checkout@v4

      - name: QEMU o‘rnatish
        uses: docker/setup-qemu-action@v3

      - name: Docker Buildx o‘rnatish
        uses: docker/setup-buildx-action@v3

      - name: Docker Hub’ga login
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker image build va push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/my-app:latest

      - name: Eskisini to‘xtatish (agar mavjud bo‘lsa)
        run: |
          docker stop my-app || true
          docker rm my-app || true

      - name: Yangi image’ni DockerHub’dan olish
        run: docker pull ${{ vars.DOCKERHUB_USERNAME }}/my-app:latest

      - name: Yangi konteynerni ishga tushirish
        run: docker run -d --name my-app -p 3000:3000 ${{ vars.DOCKERHUB_USERNAME }}/my-app:latest
